ProjeOdev/ProjeOdev/Controllers/ProjeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjeOdev.Models.context;
using ProjeOdev.Models.entity;

namespace ProjeOdev.Controllers
{
    public class ProjeController : Controller
    {
        private projeContext db = new projeContext();

        // GET: Proje
        public ActionResult Index()
        {
            int c=0;
            if (Session["yetki"]!=null)
            {
                c = (int)Session["yetki"];
                var data = db.Uyeler.Find(c);
                if (data.YetkiID == 1)
                {
                    ViewData["admin"] = "admin";
                    return View(db.Projeler.OrderByDescending(x => x.ID).ToList());
                }
                    
            }
            return View(db.Projeler.Where(x=>x.UyeID==c).ToList());
        }

        // GET: Proje/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proje proje = db.Projeler.Find(id);
            ViewBag.kisi = db.Uyeler.Find(proje.UyeID).Email;
            if (proje == null)
            {
                return HttpNotFound();
            }
            return View(proje);
        }

        // GET: Proje/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proje/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjeBaslik,ProjeIcerik,Resim,Tarih,UyeID")] Proje proje, HttpPostedFileBase foto,string icerik)
        {
            if (ModelState.IsValid)
            {
                Proje yeni = new Proje();
                if (foto != null)
                {
                    foto.SaveAs(Server.MapPath("~/img/") + foto.FileName);
                    yeni.Resim = "/img/" + foto.FileName;
                }
                else
                    yeni.Resim = "";             
                yeni.ProjeBaslik = proje.ProjeBaslik;
                yeni.ProjeIcerik = icerik;
                yeni.Tarih = DateTime.Now;
                int c = (int)Session["yetki"];
                var data = db.Uyeler.Find(c);
                yeni.UyeID =data.ID ;
                db.Projeler.Add(yeni);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(proje);
        }

        // GET: Proje/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proje proje = db.Projeler.Find(id);
            if (proje == null)
            {
                return HttpNotFound();
            }
            return View(proje);
        }

        // POST: Proje/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjeBaslik,ProjeIcerik,Resim,Tarih,UyeID")] Proje proje, HttpPostedFileBase foto, string icerik)
        {
            if (ModelState.IsValid)
            {
                Proje yeni = db.Projeler.Find(proje.ID);
                if (foto != null)
                {
                    foto.SaveAs(Server.MapPath("~/img/") + foto.FileName);
                    yeni.Resim = "/img/" + foto.FileName;
                }
                else
                    yeni.Resim = "";
                
                yeni.ProjeBaslik = proje.ProjeBaslik;
                yeni.ProjeIcerik = icerik;
               
                yeni.Tarih = DateTime.Now;
                int c = (int)Session["yetki"];
                var data = db.Uyeler.Find(c);
                yeni.UyeID = data.ID;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(proje);
        }

        // GET: Proje/Delete/5
        public ActionResult Delete(int? id)
        {
            int x = (int)Session["yetki"];
            var data = db.Uyeler.Find(x);
            if (data.YetkiID == 2)
                return RedirectToAction("Index","Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proje proje = db.Projeler.Find(id);
            if (proje == null)
            {
                return HttpNotFound();
            }
            return View(proje);
        }

        // POST: Proje/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Proje proje = db.Projeler.Find(id);
            db.Projeler.Remove(proje);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjeOdev/ProjeOdev/Views/Shared/Admin_Layout.cshtml
@{
    if (Session["yetki"] == null)
    {
        Response.Redirect("~/Home/Index");
    }
}
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Panel</title>
    @Styles.Render("~/bundles/style")
    @Scripts.Render("~/bundles/script")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ana Sayfa Dön", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Profil", "Profil","Admin")</li>
                    <li>@Html.ActionLink("Projeler", "Index","Proje")</li>
                    <li>@Html.ActionLink("Proje Ekle", "Create", "Proje")</li>
                    <li>@Html.ActionLink("Çıkış", "Cıkıs", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="container">
                @RenderBody()


            </div>
        </div>
        <hr />
        
    </div>

    @Html.Partial("~/Views/Partial/footer.cshtml")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjeOdev/ProjeOdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -ProjeniPaylaş</title>
    @Styles.Render("~/bundles/style")
    @Scripts.Render("~/bundles/script")
</head>
<body>

    <header class="header">
        <div role="navigation" class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a href="@Url.Action("Index")" class="navbar-brand">projeniPaylaş</a>
                    <div class="navbar-buttons">
                        <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
                    </div>
                </div>
                <div id="navigation" class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Ana Sayfa", "Index","Home")</li>
                        <li>@Html.ActionLink("Projeler", "Projeler","Home")</li>
                        <li>@Html.ActionLink("Vizyon", "Vizyon","Home")</li>
                    </ul>
                    @{
                        if (Session["yetki"] != null)
                        {
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Admin Paneli", "Index", "Admin")</li>
                                <li>@Html.ActionLink("Çıkış", "Cıkıs", "Admin")</li>
                            </ul>
                        }
                        else
                        {
                            <a href="#" data-toggle="modal" data-target="#login-modal" class="btn navbar-btn giris"><i class="fa fa-sign-in"></i>Log in</a>
                        }
                    }
                    
                </div>
            </div>
        </div>
        @* giriş sayfası açılır div çeklinde*@
            <div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header giris">
                            <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
                            <h4 id="Login" class="modal-title">Giriş</h4>
                        </div>
                        <div class="modal-body">
                            <form action="/Admin/Giris" method="post">
                                <div class="form-group">
                                    <input id="email" name="email" type="text" placeholder="email" class="form-control">
                                </div>
                                <div class="form-group">
                                    <input id="sifre" name="sifre" type="password" placeholder="password" class="form-control">
                                </div>
                                <p class="text-center">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                                </p>
                            </form>
                            @Html.ActionLink("Yeni Kayıt için tıklayın", "Kayit", "Admin")
                        </div>
                    </div>
                </div>
            </div>

            


    </header>
    <div class="container body-content">
        @RenderBody()

        @Html.Partial("~/Views/Partial/footer.cshtml")
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>